#!/usr/bin/env bash
#
i="1"
while [ $i -le 20 ];
do
	echo "$i"
	((i++))
	if [ $i -eq 5 ];
	then 
		echo "bad luck from China"
	elif [ $i -eq 9 ];
	then
		echo "bad luck from Japan"
	elif [ $i -eq 18 ];
	then
		echo "bad luck from Italy"
	fi
done
